name: customer-analytics

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: customer_db
    environment:
      POSTGRES_DB: customer_analytics
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: secure123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analyst -d customer_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database Administration
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: db_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@company.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  # Jupyter Data Science Environment
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: data_analytics
    environment:
      JUPYTER_TOKEN: analytics123
      GRANT_SUDO: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data:ro
      - jupyter_data:/home/jovyan/.jupyter
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: customer_cache
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
  jupyter_data:
  pgadmin_data:

networks:
  default:
    name: customer_analytics_network≈
